import type { ModelingFeedback, RevisionFact } from "@swpanel/domain";
import { MODELING_FEEDBACK_SOURCES, REVISION_FACT_SOURCES } from "@swpanel/domain";
import {
  INVOCATION_PACKAGE_SCHEMA_ID,
  PHASE4_SCHEMA_DRAFT
} from "./schema-ids.js";
import {
  Phase4ContractError,
  assertIsoTimestamp,
  assertNoUnknownKeys,
  assertNonEmptyString,
  assertOptionalNonEmptyString,
  isRecord,
  isSha256Hex
} from "./shared.js";

/**
 * Versioned Invocation Package contract (architecture.md §9.3): the complete,
 * frozen input handed to the modeling Skill for one Run attempt. The package is
 * generated by the Runner from the frozen `RunInputSnapshot` and the Input
 * Adapter provenance; the Agent never sees a client-supplied snapshot. `revisionFacts`
 * and `modelingFeedback` reuse the canonical `@swpanel/domain` memory types.
 */
export const INVOCATION_PACKAGE_CONTRACT_VERSION = 1 as const;

export interface InvocationPackageSkill {
  name: string;
  /** Approved SHA-256 of the modeling Skill definition. */
  sha256: string;
}

export interface InvocationPackageInput {
  /** Stable reference to the original drawing file artifact. */
  originalArtifactId: string;
  /** Workspace path of the adapter-derived Skill input image. */
  imagePath: string;
  /** SHA-256 of the derived image bytes. */
  imageSha256: string;
}

export interface InvocationPackageMemory {
  revisionFacts: readonly RevisionFact[];
  modelingFeedback: readonly ModelingFeedback[];
}

export interface InvocationPackageWorkspace {
  root: string;
  output: string;
}

/**
 * MVP defaults to background execution. Visible-live execution is a runtime
 * option for approved diagnostic or review workflows.
 */
export const INVOCATION_EXECUTION_VISIBILITIES = ["background", "visible"] as const;
export type InvocationExecutionVisibility = (typeof INVOCATION_EXECUTION_VISIBILITIES)[number];

export interface InvocationPackageExecution {
  visibility: InvocationExecutionVisibility;
  /** MP4 recording becomes required only when true. */
  recordMp4: boolean;
}

export interface InvocationPackage {
  contractVersion: typeof INVOCATION_PACKAGE_CONTRACT_VERSION;
  runId: string;
  skill: InvocationPackageSkill;
  input: InvocationPackageInput;
  memory: InvocationPackageMemory;
  workspace: InvocationPackageWorkspace;
  execution: InvocationPackageExecution;
}

/** JSON Schema document registering/documenting the Invocation Package contract. */
export const INVOCATION_PACKAGE_JSON_SCHEMA = {
  $schema: PHASE4_SCHEMA_DRAFT,
  $id: INVOCATION_PACKAGE_SCHEMA_ID,
  title: "SWPanel Invocation Package",
  description:
    "Frozen input handed to the modeling Skill for one Run attempt: skill identity, " +
    "adapter-derived image, Revision memory, workspace and execution options.",
  type: "object",
  additionalProperties: false,
  required: ["contractVersion", "runId", "skill", "input", "memory", "workspace", "execution"],
  properties: {
    contractVersion: { const: INVOCATION_PACKAGE_CONTRACT_VERSION },
    runId: { type: "string", minLength: 1 },
    skill: {
      type: "object",
      additionalProperties: false,
      required: ["name", "sha256"],
      properties: {
        name: { type: "string", minLength: 1 },
        sha256: { type: "string", pattern: "^[0-9a-f]{64}$" }
      }
    },
    input: {
      type: "object",
      additionalProperties: false,
      required: ["originalArtifactId", "imagePath", "imageSha256"],
      properties: {
        originalArtifactId: { type: "string", minLength: 1 },
        imagePath: { type: "string", minLength: 1 },
        imageSha256: { type: "string", pattern: "^[0-9a-f]{64}$" }
      }
    },
    memory: {
      type: "object",
      additionalProperties: false,
      required: ["revisionFacts", "modelingFeedback"],
      properties: {
        revisionFacts: {
          type: "array",
          items: {
            type: "object",
            additionalProperties: false,
            required: ["id", "revisionId", "field", "value", "source", "createdAt"],
            properties: {
              id: { type: "string", minLength: 1 },
              revisionId: { type: "string", minLength: 1 },
              field: { type: "string", minLength: 1 },
              value: { type: "string", minLength: 1 },
              unit: { type: "string", minLength: 1 },
              source: { enum: [...REVISION_FACT_SOURCES] },
              sourceRunId: { type: "string", minLength: 1 },
              createdAt: { type: "string", format: "date-time" },
              createdBy: { type: "string", minLength: 1 }
            }
          }
        },
        modelingFeedback: {
          type: "array",
          items: {
            type: "object",
            additionalProperties: false,
            required: ["id", "revisionId", "content", "source", "createdAt"],
            properties: {
              id: { type: "string", minLength: 1 },
              revisionId: { type: "string", minLength: 1 },
              modelId: { type: "string", minLength: 1 },
              reviewId: { type: "string", minLength: 1 },
              content: { type: "string", minLength: 1 },
              source: { enum: [...MODELING_FEEDBACK_SOURCES] },
              createdAt: { type: "string", format: "date-time" }
            }
          }
        }
      }
    },
    workspace: {
      type: "object",
      additionalProperties: false,
      required: ["root", "output"],
      properties: {
        root: { type: "string", minLength: 1 },
        output: { type: "string", minLength: 1 }
      }
    },
    execution: {
      type: "object",
      additionalProperties: false,
      required: ["visibility", "recordMp4"],
      properties: {
        visibility: { enum: [...INVOCATION_EXECUTION_VISIBILITIES] },
        recordMp4: { type: "boolean" }
      }
    }
  }
} as const;

const REVISION_FACT_SOURCE_SET: ReadonlySet<string> = new Set(REVISION_FACT_SOURCES);
const MODELING_FEEDBACK_SOURCE_SET: ReadonlySet<string> = new Set(MODELING_FEEDBACK_SOURCES);

function assertRevisionFact(fact: unknown): RevisionFact {
  if (!isRecord(fact)) {
    throw new Phase4ContractError("INVALID_CONTRACT", "each revision fact must be an object");
  }
  assertNoUnknownKeys(
    fact,
    ["id", "revisionId", "field", "value", "unit", "source", "sourceRunId", "createdAt", "createdBy"],
    "revision fact"
  );
  const id = assertNonEmptyString(fact, "id", "revision fact");
  const revisionId = assertNonEmptyString(fact, "revisionId", "revision fact");
  const field = assertNonEmptyString(fact, "field", "revision fact");
  const value = assertNonEmptyString(fact, "value", "revision fact");
  const unit = assertOptionalNonEmptyString(fact, "unit", "revision fact");
  if (typeof fact.source !== "string" || !REVISION_FACT_SOURCE_SET.has(fact.source)) {
    throw new Phase4ContractError(
      "INVALID_CONTRACT",
      "revision fact.source must be a revision-fact source"
    );
  }
  const sourceRunId = assertOptionalNonEmptyString(fact, "sourceRunId", "revision fact");
  const createdAt = assertIsoTimestamp(fact, "createdAt", "revision fact");
  const createdBy = assertOptionalNonEmptyString(fact, "createdBy", "revision fact");
  return {
    id,
    revisionId,
    field,
    value,
    ...(unit === undefined ? {} : { unit }),
    source: fact.source as RevisionFact["source"],
    ...(sourceRunId === undefined ? {} : { sourceRunId }),
    createdAt,
    ...(createdBy === undefined ? {} : { createdBy })
  };
}

function assertModelingFeedback(feedback: unknown): ModelingFeedback {
  if (!isRecord(feedback)) {
    throw new Phase4ContractError("INVALID_CONTRACT", "each modeling feedback must be an object");
  }
  assertNoUnknownKeys(
    feedback,
    ["id", "revisionId", "modelId", "reviewId", "content", "source", "createdAt"],
    "modeling feedback"
  );
  const id = assertNonEmptyString(feedback, "id", "modeling feedback");
  const revisionId = assertNonEmptyString(feedback, "revisionId", "modeling feedback");
  const modelId = assertOptionalNonEmptyString(feedback, "modelId", "modeling feedback");
  const reviewId = assertOptionalNonEmptyString(feedback, "reviewId", "modeling feedback");
  const content = assertNonEmptyString(feedback, "content", "modeling feedback");
  if (typeof feedback.source !== "string" || !MODELING_FEEDBACK_SOURCE_SET.has(feedback.source)) {
    throw new Phase4ContractError(
      "INVALID_CONTRACT",
      "modeling feedback.source must be a modeling-feedback source"
    );
  }
  const createdAt = assertIsoTimestamp(feedback, "createdAt", "modeling feedback");
  return {
    id,
    revisionId,
    ...(modelId === undefined ? {} : { modelId }),
    ...(reviewId === undefined ? {} : { reviewId }),
    content,
    source: feedback.source as ModelingFeedback["source"],
    createdAt
  };
}

/**
 * Strictly validates a serialized Invocation Package. Throws
 * {@link Phase4ContractError} on the first violation: contract version mismatch,
 * unknown fields, illegal enums, malformed hashes or memory items.
 */
export function validateInvocationPackage(value: unknown): InvocationPackage {
  if (!isRecord(value)) {
    throw new Phase4ContractError(
      "INVALID_CONTRACT",
      "Invocation Package must be a JSON object"
    );
  }
  assertNoUnknownKeys(
    value,
    ["contractVersion", "runId", "skill", "input", "memory", "workspace", "execution"],
    "Invocation Package"
  );
  if (value.contractVersion !== INVOCATION_PACKAGE_CONTRACT_VERSION) {
    throw new Phase4ContractError(
      "VERSION_MISMATCH",
      `Expected contractVersion ${INVOCATION_PACKAGE_CONTRACT_VERSION}, got ${JSON.stringify(value.contractVersion)}`
    );
  }
  const runId = assertNonEmptyString(value, "runId", "Invocation Package");

  const skill = value.skill;
  if (!isRecord(skill)) {
    throw new Phase4ContractError("INVALID_CONTRACT", "skill must be an object");
  }
  assertNoUnknownKeys(skill, ["name", "sha256"], "skill");
  const skillName = assertNonEmptyString(skill, "name", "skill");
  if (!isSha256Hex(skill.sha256)) {
    throw new Phase4ContractError("INVALID_CONTRACT", "skill.sha256 must be a 64-char hex digest");
  }

  const input = value.input;
  if (!isRecord(input)) {
    throw new Phase4ContractError("INVALID_CONTRACT", "input must be an object");
  }
  assertNoUnknownKeys(input, ["originalArtifactId", "imagePath", "imageSha256"], "input");
  const originalArtifactId = assertNonEmptyString(input, "originalArtifactId", "input");
  const imagePath = assertNonEmptyString(input, "imagePath", "input");
  if (!isSha256Hex(input.imageSha256)) {
    throw new Phase4ContractError("INVALID_CONTRACT", "input.imageSha256 must be a 64-char hex digest");
  }

  const memory = value.memory;
  if (!isRecord(memory)) {
    throw new Phase4ContractError("INVALID_CONTRACT", "memory must be an object");
  }
  assertNoUnknownKeys(memory, ["revisionFacts", "modelingFeedback"], "memory");
  const revisionFactsValue = memory.revisionFacts;
  if (!Array.isArray(revisionFactsValue)) {
    throw new Phase4ContractError("INVALID_CONTRACT", "memory.revisionFacts must be an array");
  }
  const revisionFacts: RevisionFact[] = [];
  for (const fact of revisionFactsValue) {
    revisionFacts.push(assertRevisionFact(fact));
  }
  const modelingFeedbackValue = memory.modelingFeedback;
  if (!Array.isArray(modelingFeedbackValue)) {
    throw new Phase4ContractError("INVALID_CONTRACT", "memory.modelingFeedback must be an array");
  }
  const modelingFeedback: ModelingFeedback[] = [];
  for (const feedback of modelingFeedbackValue) {
    modelingFeedback.push(assertModelingFeedback(feedback));
  }

  const workspace = value.workspace;
  if (!isRecord(workspace)) {
    throw new Phase4ContractError("INVALID_CONTRACT", "workspace must be an object");
  }
  assertNoUnknownKeys(workspace, ["root", "output"], "workspace");
  const workspaceRoot = assertNonEmptyString(workspace, "root", "workspace");
  const output = assertNonEmptyString(workspace, "output", "workspace");

  const execution = value.execution;
  if (!isRecord(execution)) {
    throw new Phase4ContractError("INVALID_CONTRACT", "execution must be an object");
  }
  assertNoUnknownKeys(execution, ["visibility", "recordMp4"], "execution");
  if (
    typeof execution.visibility !== "string" ||
    !INVOCATION_EXECUTION_VISIBILITIES.includes(execution.visibility as never)
  ) {
    throw new Phase4ContractError(
      "INVALID_CONTRACT",
      "execution.visibility must be one of background, visible"
    );
  }
  if (typeof execution.recordMp4 !== "boolean") {
    throw new Phase4ContractError("INVALID_CONTRACT", "execution.recordMp4 must be a boolean");
  }

  return {
    contractVersion: INVOCATION_PACKAGE_CONTRACT_VERSION,
    runId,
    skill: { name: skillName, sha256: skill.sha256 },
    input: { originalArtifactId, imagePath, imageSha256: input.imageSha256 },
    memory: {
      revisionFacts,
      modelingFeedback
    },
    workspace: { root: workspaceRoot, output },
    execution: {
      visibility: execution.visibility as InvocationExecutionVisibility,
      recordMp4: execution.recordMp4
    }
  };
}
