/**
 * Common serialization-friendly types shared across query, command, event and
 * IPC contracts. Every DTO in this package is JSON-safe.
 */

/** Stable business identifiers generated by the Runner. */
export interface EntityId {
  drawingId?: string;
  revisionId?: string;
  runId?: string;
  modelId?: string;
  reviewId?: string;
  clarificationRequestId?: string;
  artifactId?: string;
  costReportId?: string;
}

/** Cursor-based paging envelope. `nextCursor` is null on the last page. */
export interface Page<T> {
  items: readonly T[];
  nextCursor: string | null;
}

/** Wrapper for serialized domain result values. */
export interface DomainResult<T> {
  ok: true;
  data: T;
}

export interface DomainErrorResult {
  ok: false;
  error: {
    code: string;
    message: string;
  };
}

export type Result<T> = DomainResult<T> | DomainErrorResult;

export function ok<T>(data: T): DomainResult<T> {
  return { ok: true, data };
}

export function fail(code: string, message: string): DomainErrorResult {
  return { ok: false, error: { code, message } };
}
